version: "2"

run:
  timeout: 2m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  goimports:
    local-prefixes: github.com/mindful-minutes/mindful-minutes-api

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 3