version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      colors: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 3