version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      colors: true

linters:
  enable:
    - asciicheck
    - copyloopvar
    - exhaustive
    - forbidigo
    - gocyclo
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - testpackage
    - unconvert
    - wastedassign
    - whitespace

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
